### PR TITLE
Add somesy and fair-python-cookiecutter to awesomelist

### PR DESCRIPTION
**Pull request by broeder-j**

### CODE REVIEW

**Comment by broeder-j** [comment]
Maybe this link to the github zenodo integration is nicer: https://coderefinery.github.io/github-without-command-line/doi/

**Comment by geyslein** [comment]
hey, thanks for adding. just one request, we listed the HERMES project already in the awesome list about Science: https://github.com/hifis-net/awesome-rse-science 

Could you change link and wording in your PR so that HERMES(or whatever the tool is called) refers to the tool/workflow rather than to the project? Thanks

**Comment by broeder-j** [comment]
Hi @geyslein , I did. please review again.

**Review by geyslein — APPROVED** [review]

**Comment by geyslein** [comment]
thanks @broeder-j

**Pull request merged**
